import { Loader2, Copy, Check, Link2, ArrowUpRight, QrCode, BarChart3, Trash2 } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import toast from 'react-hot-toast'
import { twMerge } from 'tailwind-merge'
export const Button=({children,className='',loading,...props})=><motion.button whileHover={{y:-2}} whileTap={{scale:.97}} disabled={loading||props.disabled} className={twMerge('inline-flex items-center justify-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-semibold text-white shadow-glow transition hover:bg-indigo-500 disabled:opacity-60',className)} {...props}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:children}</motion.button>
export const CopyButton=({value})=>{const [done,setDone]=useState(false); const copy=async()=>{await navigator.clipboard.writeText(value);setDone(true);toast.success('Link copied');setTimeout(()=>setDone(false),1500)};return <button aria-label="Copy link" onClick={copy} className="rounded-xl border border-white/10 p-2 text-gray-400 transition hover:border-primary/60 hover:text-white">{done?<Check className="h-4 w-4 text-emerald-400"/>:<Copy className="h-4 w-4"/>}</button>}
export const SectionTitle=({eyebrow,title,text})=><div className="mx-auto mb-12 max-w-2xl text-center"><p className="mb-3 text-sm font-semibold uppercase tracking-[.22em] text-cyan">{eyebrow}</p><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h2>{text&&<p className="mt-4 text-gray-400">{text}</p>}</div>
export const Stat=({label,value,icon:Icon,change})=><div className="glass rounded-3xl p-5"><div className="mb-7 flex items-start justify-between"><span className="text-sm text-gray-400">{label}</span><span className="rounded-xl bg-primary/15 p-2 text-indigo-300"><Icon className="h-4 w-4"/></span></div><p className="text-2xl font-semibold">{value}</p>{change&&<p className="mt-2 text-xs text-emerald-400">{change} vs last week</p>}</div>
export const UrlCard=({item})=><motion.article whileHover={{y:-4}} className="glass rounded-3xl p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm text-gray-400">{item.original}</p><div className="mt-2 flex items-center gap-2"><Link2 className="h-4 w-4 text-cyan"/><a href={item.short} target="_blank" rel="noreferrer" className="font-medium text-white hover:text-cyan">{item.short}</a><CopyButton value={item.short}/></div></div><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-gray-400">{item.clicks} clicks</span></div><div className="mt-5 flex justify-between border-t border-white/5 pt-4 text-xs text-gray-500"><span>{item.created}</span><div className="flex gap-2"><button aria-label="QR Code"><QrCode className="h-4 w-4"/></button><button aria-label="Analytics"><BarChart3 className="h-4 w-4"/></button><button aria-label="Visit"><ArrowUpRight className="h-4 w-4"/></button><button aria-label="Delete" className="hover:text-red-400"><Trash2 className="h-4 w-4"/></button></div></div></motion.article>
